### PR TITLE
Enable testing on python 3.4, 3.5, 3.6, and PyPy3

### PR DESCRIPTION
**Pull request by altendky**
Issue #28

### CODE REVIEW

**Comment by altendky** [comment]
I assume this'll fail, but I like to get server-side testing started sooner than later.  We'll see what comes of this.

**Comment by Julian** [comment]
👍

**Comment by Julian** [comment]
(Well, I guess the reason I didn't do this before is I don't want to leave the build saying it's failing indefinitely :P, so hopefully you do intend to knock out #28)

**Comment by altendky** [comment]
So...  didn't really mean for this to get pulled yet...  sort of a shortcoming of PR's it seems to me.  There's no 'yes I really want this merged' state vs. 'I want to talk about this and see what the tests do'.

**Comment by Julian** [comment]
Ah -- fair enough. Well, can always roll it back if need be.

**Pull request merged**
